version: '3'
services:
    app:
      build:
        context: .
        dockerfile: ./Dockerfile
      container_name: divine-vault-api
      ports:
        - 3000:3000
      environment:
        MONGO_URI: mongodb://mongodb:27017/divine-vault
      depends_on:
        - db
    db:
      image: mongo:latest
      container_name: mongodb
      restart: always
      environment:
        MONGODB_DATABASE: divine-vault
      ports:
        - 27017:27017
      volumes:
      - ./mongodb_data:/data/db

volumes:
  mongodb_data: