version: '3'
services:
    db:
      image: mongo:latest
      container_name: mongodb
      restart: always
      environment:
        MONGODB_DATABASE: divine-vault
      ports:
        - 27017:27017
      volumes:
      - ./mongodb_data:/data/db

volumes:
  mongodb_data: