service: jaifdev

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  stage: production
  region: us-east-2
  memorySize: 2048
  logRetentionInDays: 1
  timeout: 30

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
         method: any
         path: /{proxi+}

plugins:
  - serverless-jetpack
  - serverless-offline