service: jaifdev

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  stage: prod
  region: us-east-2
  memorySize: 1024
  logRetentionInDays: 1
  timeout: 60

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: '{proxy+}'

plugins:
  - serverless-jetpack
  - serverless-offline
  - serverless-plugin-optimize

custom:
    optimize:
        external: ['swagger-ui-dist']